-- ══════════════════════════════════════════════════════════════════════════
-- NAIWANSOOK FOODCOST — ใบโอนย้ายสินทรัพย์ระหว่างสาขา. รันครั้งเดียวใน Supabase SQL editor
--
-- ทำไมต้องมี: เดิมการโอนย้ายสินทรัพย์แก้แถวในตาราง assets ตรงๆ (ย้ายสาขา หรือแยกแถวใหม่)
-- แล้วจบ — ไม่มีเอกสารเก็บไว้เลย ผลคือ
--   • ไม่มีใบให้เซ็นรับ-ส่ง (ของหายระหว่างทางแล้วไม่รู้ว่าใครรับผิดชอบ)
--   • ดูย้อนหลังไม่ได้ว่าของชิ้นนี้เคยอยู่สาขาไหน ใครสั่งย้าย เมื่อไหร่
--   • ทะเบียนทรัพย์สินฝั่งบัญชีเปลี่ยนสาขาโดยไม่มีที่มา
--
-- ตารางนี้เก็บ "หัวใบ + รายการ" ของการโอนแต่ละครั้ง (ไม่ได้ไปแทนที่ตาราง assets
-- ซึ่งยังเป็นตัวจริงของยอดคงเหลือ) จึงเป็นบันทึกเชิงประวัติ ลบไม่กระทบจำนวนสินทรัพย์
-- ══════════════════════════════════════════════════════════════════════════

create table if not exists public.asset_transfers (
  id              bigint generated by default as identity primary key,
  transfer_no     text unique,        -- AT-YYYYMM-xxxxx
  from_branch_id  int,
  to_branch_id    int,
  from_branch_name text,              -- เก็บชื่อ ณ ตอนโอน เพื่อให้ใบเก่ายังอ่านได้ถ้าสาขาถูกปิด/เปลี่ยนชื่อ
  to_branch_name  text,
  items           jsonb not null default '[]'::jsonb,
  -- [{asset_id, new_asset_id, name, category, qty, cost_per_unit, total_cost}]
  total_cost      numeric not null default 0,
  note            text,
  transferred_by  text,
  created_at      timestamptz not null default now()
);
create index if not exists asset_transfers_recent on public.asset_transfers (created_at desc);
create index if not exists asset_transfers_from on public.asset_transfers (from_branch_id, created_at desc);
create index if not exists asset_transfers_to on public.asset_transfers (to_branch_id, created_at desc);

-- Supabase เปิด RLS ให้ตารางใหม่อัตโนมัติ — ระบบนี้ปิด RLS ทุกตาราง ต้องปิดให้ตรงกัน
-- ⚠️ ถ้าบันทึกใบโอนแล้วเจอ error 401/42501 ให้รันบรรทัดนี้แยกอีกครั้ง
alter table public.asset_transfers disable row level security;

-- ตรวจ:  select transfer_no, from_branch_name, to_branch_name, total_cost, created_at
--        from public.asset_transfers order by created_at desc limit 20;
