-- ══════════════════════════════════════════════════════════════════════════
-- NAIWANSOOK FOODCOST — เก็บ "ยอดยกมา" ของงวดแรกที่ส่งเข้าระบบบัญชี
-- รันครั้งเดียวใน Supabase SQL editor (ก่อนเปิด cron รายวัน)
--
-- ทำไมต้องมี: รายงานสินค้าและวัตถุดิบ (ม.87) คิดว่า
--     ใช้ไป (ต้นทุนวัตถุดิบ) = ยกมา + ซื้อระหว่างงวด − ตรวจนับปลายงวด
-- งวดแรกยังไม่มี "ยกมา" ในระบบบัญชี ถ้าปล่อยเป็น 0 ต้นทุนจะต่ำกว่าจริงทั้งก้อน
-- (เท่ากับมูลค่าสต๊อกทั้งบริษัท ~1.5 ล้าน) งวดถัดๆ ไปไม่ต้องใช้ตารางนี้ เพราะบัญชี
-- ยกยอดตรวจนับงวดก่อนมาให้เอง
--
-- ทำไมเก็บใน DB ไม่ใช่ในโค้ด: ค่านี้ต้อง "นิ่ง" (ส่งซ้ำทุกวันต้องได้เลขเดิม ไม่งั้น
-- ยอดยกมาจะขยับตามวันที่ยิง) และ repo เป็น PUBLIC จึงไม่ควรมีมูลค่าสต๊อกรายสาขาอยู่ในนั้น
--
-- ลำดับการใช้งาน:
--   1. รันไฟล์นี้ (สร้างตารางเปล่า)
--   2. ยิงครั้งเดียวเพื่อ "จับภาพ" มูลค่าปัจจุบันเป็นยอดยกมาของงวดนี้:
--        /api/sliptrack-sweep?job=daily&capture_opening=1&key=<YOUR_SWEEP_KEY>
--      (ยิงซ้ำไม่ทับของเดิม — งวดไหนมีค่าแล้วจะข้าม)
--   3. ตรวจค่าที่จับได้:  select * from public.sliptrack_opening order by branch, account;
--   4. ค่อยเปิด cron รายวัน (sql/sliptrack-daily-cron.sql)
-- ══════════════════════════════════════════════════════════════════════════

create table if not exists public.sliptrack_opening (
  id          bigint generated by default as identity primary key,
  period      text not null,              -- งวด YYYY-MM
  branch      text not null,              -- ชื่อสาขาแบบที่ส่งให้บัญชี (canonical)
  account     text not null,              -- ชื่อหมวดบัญชีเต็มพร้อมรหัส
  value       numeric not null default 0, -- มูลค่ายกมา (บาท)
  captured_at timestamptz not null default now(),
  note        text,
  unique (period, branch, account)
);

alter table public.sliptrack_opening disable row level security;   -- ให้เข้ากับตารางอื่นในระบบ (RLS ปิดทั้งหมด)

-- ถ้าจับภาพผิดงวด/อยากจับใหม่ ให้ลบงวดนั้นทิ้งก่อนแล้วยิง capture ใหม่:
--   delete from public.sliptrack_opening where period = '2026-07';
