-- ══════════════════════════════════════════════════════════════════════════
-- NAIWANSOOK FOODCOST — stock movement log. Run ONCE in the Supabase SQL editor.
--
-- stock_logs only records COUNTS (prev→new when someone counts). Every OTHER change —
-- receiving a PO, shipping/transferring, a dispute clamp, a cancel refund, WASTE, and the
-- SOP cascade that quietly consumes sub-ingredients by the gram — left NO trace, so a
-- counted-as-integer item turning up fractional the next day was impossible to explain.
--
-- This is an OBSERVATIONAL log: it records each stock delta with a reason. It never changes
-- how stock is computed (writing a row can only fail to log; it can't corrupt a quantity).
-- ══════════════════════════════════════════════════════════════════════════
create table if not exists public.stock_movements (
  id              bigint generated by default as identity primary key,
  branch_id       int,
  ingredient_id   bigint,
  ingredient_name text,
  unit            text,
  delta           numeric,        -- signed: + added to this branch, − removed from it
  reason          text,           -- human label: 'รับเข้า PO-x' | 'จัดส่ง PO-x' | 'SOP: ผลิต ซอสกะเพรา' | 'ของเสีย' | 'คืนสต๊อก (ยกเลิก)' …
  ref_type        text,           -- 'po' | 'transfer' | 'waste' | 'sop' | 'rollback' | 'dispute' | 'order'
  ref_id          text,
  by_user         text,
  created_at      timestamptz not null default now()
);
create index if not exists stock_movements_lookup on public.stock_movements (branch_id, ingredient_id, created_at desc);
create index if not exists stock_movements_recent on public.stock_movements (created_at desc);
alter table public.stock_movements disable row level security;   -- match the rest of the schema (RLS off)

-- Trace one ingredient at one branch anytime:
-- select created_at, delta, reason, ref_type, by_user
-- from public.stock_movements
-- where branch_id = 6 and ingredient_id = 63
-- order by created_at desc limit 50;
